### ISSUE TITLE
DSS in XML

### ISSUE THREAD

**Issue by normansimonr** [ETCBC/dss#1]
Hi. Is there a way to access the text of the DSS in XML format? For example, in something similar to TEI? Thanks.

**Comment by MartijnNaaijer** [comment]
Hi Norman, the dataset is presently only available as a Text-Fabric dataset. I do not plan to convert it to any other format. Regards, Martijn

**Comment by dirkroorda** [comment]
To add to this: the conversion from TF to TEI is potentially difficult, because you want to translate the nodes of TF to elements in the XML. But nodes may overlap, and elements not, so you have to unravel the overlapping nodes into fragments and wrap them in elements. This can become very cumbersome.

**Comment by normansimonr** [comment]
Ok, thank you so much. Or is there a way to convert it to some other format, like CSV for example? I'm not familiar with Text Fabric but I know Python and Jupyter notebooks. Is there like a recipe or something similar that I could use for that?

**Comment by MartijnNaaijer** [comment]
You can easily make csv files with the data. Check e.g. https://nbviewer.org/github/etcbc/dss/blob/master/tutorial/exportExcel.ipynb
Note that there are many intricacies in the data, see the feature docs: https://github.com/ETCBC/dss/blob/master/docs/transcription.md

**Comment by normansimonr** [comment]
@dirkroorda Thank you very much!
